# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PositiveEnergy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya/RxSwift', '~> 11.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Kingfisher', '~> 4.8.0'
  pod 'SDCycleScrollView', '~> 1.75'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'MJRefresh' ,'~> 3.1.15'
  
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/ReducedWeChat'
  pod 'UMCShare/Social/ReducedQQ'
  pod 'UMCCommon'

  target 'PositiveEnergyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PositiveEnergyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
